spring:
  rabbitmq:
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
        acknowledge-mode: auto
        retry:
          enabled: true # 开启超时重试机制
          initial-interval: 1000ms # 失败后的初始等待时间
          multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
          max-attempts: 3 # 最大重试次数
          stateless: true
    host: 192.168.76.138 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123321 # 密码
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS